// Country calling codes for the phone number field.
// `iso` is the ISO 3166-1 alpha-2 code, used to derive the flag emoji.

export interface Country {
  iso: string
  name: string
  dialCode: string
  flag: string
}

function isoToFlag(iso2: string) {
  return iso2
    .toUpperCase()
    .replace(/./g, (char) => String.fromCodePoint(char.charCodeAt(0) + 127397))
}

const raw: [string, string, string][] = [
  ['IN', 'India', '+91'],
  ['US', 'United States', '+1'],
  ['CA', 'Canada', '+1'],
  ['GB', 'United Kingdom', '+44'],
  ['AU', 'Australia', '+61'],
  ['AE', 'United Arab Emirates', '+971'],
  ['SG', 'Singapore', '+65'],
  ['DE', 'Germany', '+49'],
  ['FR', 'France', '+33'],
  ['NL', 'Netherlands', '+31'],
  ['IE', 'Ireland', '+353'],
  ['IT', 'Italy', '+39'],
  ['ES', 'Spain', '+34'],
  ['PT', 'Portugal', '+351'],
  ['CH', 'Switzerland', '+41'],
  ['SE', 'Sweden', '+46'],
  ['NO', 'Norway', '+47'],
  ['DK', 'Denmark', '+45'],
  ['FI', 'Finland', '+358'],
  ['PL', 'Poland', '+48'],
  ['AT', 'Austria', '+43'],
  ['BE', 'Belgium', '+32'],
  ['GR', 'Greece', '+30'],
  ['CZ', 'Czech Republic', '+420'],
  ['RO', 'Romania', '+40'],
  ['HU', 'Hungary', '+36'],
  ['RU', 'Russia', '+7'],
  ['UA', 'Ukraine', '+380'],
  ['TR', 'Turkey', '+90'],
  ['IL', 'Israel', '+972'],
  ['SA', 'Saudi Arabia', '+966'],
  ['QA', 'Qatar', '+974'],
  ['KW', 'Kuwait', '+965'],
  ['BH', 'Bahrain', '+973'],
  ['OM', 'Oman', '+968'],
  ['EG', 'Egypt', '+20'],
  ['ZA', 'South Africa', '+27'],
  ['NG', 'Nigeria', '+234'],
  ['KE', 'Kenya', '+254'],
  ['GH', 'Ghana', '+233'],
  ['TZ', 'Tanzania', '+255'],
  ['ET', 'Ethiopia', '+251'],
  ['MA', 'Morocco', '+212'],
  ['DZ', 'Algeria', '+213'],
  ['TN', 'Tunisia', '+216'],
  ['PK', 'Pakistan', '+92'],
  ['BD', 'Bangladesh', '+880'],
  ['LK', 'Sri Lanka', '+94'],
  ['NP', 'Nepal', '+977'],
  ['CN', 'China', '+86'],
  ['JP', 'Japan', '+81'],
  ['KR', 'South Korea', '+82'],
  ['HK', 'Hong Kong', '+852'],
  ['TW', 'Taiwan', '+886'],
  ['MY', 'Malaysia', '+60'],
  ['TH', 'Thailand', '+66'],
  ['VN', 'Vietnam', '+84'],
  ['PH', 'Philippines', '+63'],
  ['ID', 'Indonesia', '+62'],
  ['NZ', 'New Zealand', '+64'],
  ['BR', 'Brazil', '+55'],
  ['MX', 'Mexico', '+52'],
  ['AR', 'Argentina', '+54'],
  ['CL', 'Chile', '+56'],
  ['CO', 'Colombia', '+57'],
  ['PE', 'Peru', '+51'],
  ['VE', 'Venezuela', '+58'],
  ['EC', 'Ecuador', '+593'],
  ['UY', 'Uruguay', '+598'],
  ['PY', 'Paraguay', '+595'],
  ['BO', 'Bolivia', '+591'],
  ['CR', 'Costa Rica', '+506'],
  ['PA', 'Panama', '+507'],
  ['DO', 'Dominican Republic', '+1'],
  ['JM', 'Jamaica', '+1'],
  ['TT', 'Trinidad and Tobago', '+1'],
  ['GT', 'Guatemala', '+502'],
  ['HN', 'Honduras', '+504'],
  ['SV', 'El Salvador', '+503'],
  ['NI', 'Nicaragua', '+505'],
  ['CU', 'Cuba', '+53'],
  ['IS', 'Iceland', '+354'],
  ['LU', 'Luxembourg', '+352'],
  ['MT', 'Malta', '+356'],
  ['CY', 'Cyprus', '+357'],
  ['HR', 'Croatia', '+385'],
  ['SI', 'Slovenia', '+386'],
  ['SK', 'Slovakia', '+421'],
  ['BG', 'Bulgaria', '+359'],
  ['RS', 'Serbia', '+381'],
  ['LT', 'Lithuania', '+370'],
  ['LV', 'Latvia', '+371'],
  ['EE', 'Estonia', '+372'],
  ['BY', 'Belarus', '+375'],
  ['GE', 'Georgia', '+995'],
  ['AM', 'Armenia', '+374'],
  ['AZ', 'Azerbaijan', '+994'],
  ['KZ', 'Kazakhstan', '+7'],
  ['UZ', 'Uzbekistan', '+998'],
  ['JO', 'Jordan', '+962'],
  ['LB', 'Lebanon', '+961'],
  ['IQ', 'Iraq', '+964'],
  ['IR', 'Iran', '+98'],
  ['AF', 'Afghanistan', '+93'],
  ['MM', 'Myanmar', '+95'],
  ['KH', 'Cambodia', '+855'],
  ['LA', 'Laos', '+856'],
  ['MN', 'Mongolia', '+976'],
  ['BT', 'Bhutan', '+975'],
  ['MV', 'Maldives', '+960'],
  ['FJ', 'Fiji', '+679'],
  ['PG', 'Papua New Guinea', '+675'],
  ['ZM', 'Zambia', '+260'],
  ['ZW', 'Zimbabwe', '+263'],
  ['UG', 'Uganda', '+256'],
  ['RW', 'Rwanda', '+250'],
  ['SN', 'Senegal', '+221'],
  ['CI', 'Ivory Coast', '+225'],
  ['CM', 'Cameroon', '+237'],
  ['AO', 'Angola', '+244'],
  ['MZ', 'Mozambique', '+258'],
  ['NA', 'Namibia', '+264'],
  ['BW', 'Botswana', '+267'],
  ['MU', 'Mauritius', '+230'],
]

export const countries: Country[] = raw
  .map(([iso, name, dialCode]): Country => ({ iso, name, dialCode, flag: isoToFlag(iso) }))
  .sort((a, b) => a.name.localeCompare(b.name))

export { isoToFlag }
